name: List GCS Bucket Contents

on:
  workflow_dispatch:

jobs:
  list_bucket_contents:
    runs-on: ubuntu-latest

  #   name: GCS Deployment
  # deploy:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: fiery-bit-420221

    - uses: 'google-github-actions/auth@v2'
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: fiery-bit-420221


    - name: Deploy via GCS
      run: |
        gsutil -m rm -rf gs://tftestpr || echo "$?"
        gsutil -m cp -r * gs://tftestpr

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Set up Google Cloud SDK
    #     uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1
    #     with:
    #       version: 'latest'
    #       service_account_key: ${{ secrets.GCP_SA_KEY }}
    #       project_id: fiery-bit-420221
    #       export_default_credentials: true

    #   - name: List GCS Bucket Contents
    #     run: |
    #       gsutil ls gs://your-bucket-name
